version: '3'
  
silent: true

tasks:
  default:
    aliases:
      - list
    desc: List all tasks
    cmd: task -l

  build:
    desc: Build the project
    cmds: 
      - cp .env.example .env
      - docker compose build

  run:
    desc: "Run the project. The first parameter is the LTL formula, and the second and subsequent parameters are response events."
          
    cmds: 
      - docker compose run -it --rm cmake bash -c "cd /root/ffs/build && cmake .. && make && ./ffs"